import Head from "next/head";
import { selectGlobalState } from "../../app/GlobalSlice";
import { useAppSelector } from "../../app/store";
import { selectUserState } from "../../app/UserSlice";
import Alert from "../components/global/Alert";

type Props = { children: JSX.Element | JSX.Element[] | null, additionalStyle: string, pageTitle: string }

export default function DefaultLayout({ children, additionalStyle, pageTitle = 'Healen' }: Props) {
  const { isLoggedIn, userInfo } = useAppSelector(selectUserState);

  return <>
    <Head>
      <title>{pageTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={`w-full min-h-screen ${additionalStyle}`}>
      <Alert text="AAAAAAAAAAA"/>
      {children}
    </main>
  </>
}